import {
  type AsyncDatabaseAdapter,
  type AsyncDatabaseSession,
} from './asyncAdapter';
import {
  DEFAULT_WORKSPACE_ID,
  DEFAULT_WORKSPACE_NAME,
  DEFAULT_WORKSPACE_SLUG,
} from './workspaceDefaults';
import { POSTGRES_IDENTITY_MIGRATIONS } from './postgres-migrations/identity';
import { POSTGRES_AGENT_LIFECYCLE_MIGRATIONS } from './postgres-migrations/agentLifecycle';
import { POSTGRES_BILLING_MIGRATIONS } from './postgres-migrations/billing';
import { POSTGRES_KNOWLEDGE_MIGRATIONS } from './postgres-migrations/knowledge';
import { POSTGRES_OPERATIONS_MIGRATIONS } from './postgres-migrations/operations';
import { POSTGRES_PAYMENT_MIGRATIONS } from './postgres-migrations/payments';
import { POSTGRES_USAGE_MIGRATIONS } from './postgres-migrations/usage';
import { POSTGRES_WORKSPACE_MIGRATIONS } from './postgres-migrations/workspaces';

export interface PostgresMigration {
  id: string;
  up: (database: AsyncDatabaseSession) => Promise<void>;
}

const MIGRATION_LOCK_ID = 1_904_202_026;

async function applyPlatformMetadata(database: AsyncDatabaseSession): Promise<void> {
  await database.execute({
    text: `
      CREATE TABLE IF NOT EXISTS workspaces (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        slug TEXT NOT NULL UNIQUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      );

      CREATE TABLE IF NOT EXISTS agents (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        workspace_id INTEGER NOT NULL DEFAULT ${DEFAULT_WORKSPACE_ID},
        name TEXT NOT NULL,
        slug TEXT NOT NULL UNIQUE,
        description TEXT NOT NULL DEFAULT '',
        path TEXT NOT NULL,
        status TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
      );

      CREATE TABLE IF NOT EXISTS agent_configs (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        agent_id INTEGER NOT NULL UNIQUE,
        config_json TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(agent_id) REFERENCES agents(id) ON DELETE CASCADE
      );

      CREATE TABLE IF NOT EXISTS runs (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        agent_id INTEGER NOT NULL,
        workspace_id INTEGER NOT NULL DEFAULT ${DEFAULT_WORKSPACE_ID},
        input TEXT NOT NULL,
        status TEXT NOT NULL,
        started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        ended_at TIMESTAMPTZ,
        FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
        FOREIGN KEY(agent_id) REFERENCES agents(id) ON DELETE CASCADE
      );

      CREATE TABLE IF NOT EXISTS stream_events (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        run_id INTEGER NOT NULL,
        event_type TEXT NOT NULL,
        node TEXT NOT NULL DEFAULT '',
        payload_json TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(run_id) REFERENCES runs(id) ON DELETE CASCADE
      );

      CREATE TABLE IF NOT EXISTS documents (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        agent_id INTEGER NOT NULL,
        workspace_id INTEGER NOT NULL DEFAULT ${DEFAULT_WORKSPACE_ID},
        filename TEXT NOT NULL,
        hash TEXT NOT NULL,
        status TEXT NOT NULL,
        collection TEXT NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
        FOREIGN KEY(agent_id) REFERENCES agents(id) ON DELETE CASCADE
      );

      CREATE TABLE IF NOT EXISTS provider_configs (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        workspace_id INTEGER NOT NULL DEFAULT ${DEFAULT_WORKSPACE_ID},
        name TEXT NOT NULL UNIQUE,
        type TEXT NOT NULL,
        config_json TEXT NOT NULL,
        secret_ref TEXT NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
      );
    `,
  });
  await database.execute({
    text: `
      INSERT INTO workspaces (id, name, slug)
      VALUES ($1, $2, $3)
      ON CONFLICT (id) DO NOTHING;
    `,
    values: [DEFAULT_WORKSPACE_ID, DEFAULT_WORKSPACE_NAME, DEFAULT_WORKSPACE_SLUG],
  });
  await database.execute({
    text: `
      SELECT setval(
        pg_get_serial_sequence('workspaces', 'id'),
        GREATEST((SELECT MAX(id) FROM workspaces), $1),
        true
      );
    `,
    values: [DEFAULT_WORKSPACE_ID],
  });
}

export const POSTGRES_MIGRATIONS: readonly PostgresMigration[] = [
  {
    id: '001_platform_metadata',
    up: applyPlatformMetadata,
  },
  ...POSTGRES_IDENTITY_MIGRATIONS,
  ...POSTGRES_OPERATIONS_MIGRATIONS,
  ...POSTGRES_KNOWLEDGE_MIGRATIONS,
  ...POSTGRES_WORKSPACE_MIGRATIONS,
  ...POSTGRES_AGENT_LIFECYCLE_MIGRATIONS,
  ...POSTGRES_BILLING_MIGRATIONS,
  ...POSTGRES_PAYMENT_MIGRATIONS,
  ...POSTGRES_USAGE_MIGRATIONS,
];

function validateMigrations(migrations: readonly PostgresMigration[]): void {
  let previous = '';
  for (const migration of migrations) {
    if (!/^\d{3}_[a-z0-9_]+$/.test(migration.id)) {
      throw new Error(`invalid PostgreSQL migration id: ${migration.id}`);
    }
    if (migration.id <= previous) {
      throw new Error(`PostgreSQL migrations are duplicated or out of order: ${migration.id}`);
    }
    previous = migration.id;
  }
}

export async function runPostgresMigrations(
  database: AsyncDatabaseAdapter,
  migrations: readonly PostgresMigration[] = POSTGRES_MIGRATIONS,
): Promise<void> {
  validateMigrations(migrations);
  await database.transaction(async (transaction) => {
    await transaction.execute({
      text: 'SELECT pg_advisory_xact_lock($1);',
      values: [MIGRATION_LOCK_ID],
    });
    await transaction.execute({
      text: `
        CREATE TABLE IF NOT EXISTS schema_migrations (
          id TEXT PRIMARY KEY,
          applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
      `,
    });
    const rows = await transaction.query<{ id: string }>({
      text: 'SELECT id FROM schema_migrations ORDER BY id ASC;',
    });
    const applied = new Set(rows.map((row) => row.id));

    for (const migration of migrations) {
      if (applied.has(migration.id)) continue;
      await migration.up(transaction);
      await transaction.execute({
        text: 'INSERT INTO schema_migrations (id) VALUES ($1);',
        values: [migration.id],
      });
    }
  });
}
