import { type PostgresMigration } from '../postgresMigrations';

export const POSTGRES_ACCOUNT_IDENTITY_MIGRATIONS: readonly PostgresMigration[] = [
  {
    id: '019_account_identity_lifecycle',
    up: async (database) => {
      await database.execute({
        text: `
          ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMPTZ;
          UPDATE users
          SET email_verified_at = COALESCE(email_verified_at, CURRENT_TIMESTAMP);

          CREATE TABLE IF NOT EXISTS account_action_tokens (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            purpose TEXT NOT NULL CHECK(purpose IN ('verify_email', 'reset_password')),
            token_hash TEXT NOT NULL UNIQUE,
            payload_json TEXT NOT NULL DEFAULT '{}',
            expires_at TIMESTAMPTZ NOT NULL,
            used_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
          );

          CREATE TABLE IF NOT EXISTS account_email_outbox (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            template TEXT NOT NULL CHECK(template IN ('verify_email', 'reset_password')),
            recipient_email TEXT NOT NULL,
            payload_json TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending'
              CHECK(status IN ('pending', 'delivering', 'delivered', 'failed', 'superseded')),
            attempts INTEGER NOT NULL DEFAULT 0 CHECK(attempts >= 0),
            next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_error TEXT NOT NULL DEFAULT '',
            delivered_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
          );

          CREATE TABLE IF NOT EXISTS workspace_onboarding (
            workspace_id INTEGER PRIMARY KEY,
            owner_user_id INTEGER NOT NULL UNIQUE,
            selected_plan_key TEXT NOT NULL CHECK(selected_plan_key IN ('free', 'pro')),
            state TEXT NOT NULL DEFAULT 'pending_email' CHECK(state IN ('pending_email', 'active')),
            activated_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(owner_user_id) REFERENCES users(id) ON DELETE CASCADE
          );

          CREATE INDEX IF NOT EXISTS account_action_tokens_lookup_idx
            ON account_action_tokens(purpose, token_hash, expires_at);
          CREATE INDEX IF NOT EXISTS account_email_outbox_dispatch_idx
            ON account_email_outbox(status, next_attempt_at, id);
        `,
      });
    },
  },
];

export const POSTGRES_EMAIL_MIGRATIONS: readonly PostgresMigration[] = [
  {
    id: '021_transactional_email_delivery',
    up: async (database) => {
      await database.execute({
        text: `
          ALTER TABLE account_email_outbox ADD COLUMN IF NOT EXISTS provider TEXT NOT NULL DEFAULT '';
          ALTER TABLE account_email_outbox ADD COLUMN IF NOT EXISTS provider_message_id TEXT NOT NULL DEFAULT '';
          ALTER TABLE account_email_outbox ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMPTZ;
          ALTER TABLE account_email_outbox ADD COLUMN IF NOT EXISTS dead_lettered_at TIMESTAMPTZ;
          ALTER TABLE account_email_outbox ADD COLUMN IF NOT EXISTS last_provider_status TEXT NOT NULL DEFAULT '';

          CREATE TABLE IF NOT EXISTS account_email_delivery_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            provider TEXT NOT NULL,
            provider_event_id TEXT NOT NULL,
            provider_message_id TEXT NOT NULL,
            outbox_id INTEGER,
            event_type TEXT NOT NULL CHECK(event_type IN (
              'accepted', 'delivered', 'delayed', 'bounced', 'complained', 'rejected'
            )),
            occurred_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(provider, provider_event_id)
          );

          CREATE UNIQUE INDEX IF NOT EXISTS account_email_provider_message_idx
            ON account_email_outbox(provider, provider_message_id)
            WHERE provider_message_id <> '';
          CREATE INDEX IF NOT EXISTS account_email_delivery_event_message_idx
            ON account_email_delivery_events(provider, provider_message_id, id);

          DROP TRIGGER IF EXISTS account_email_delivery_events_immutable
            ON account_email_delivery_events;
          CREATE TRIGGER account_email_delivery_events_immutable
            BEFORE UPDATE OR DELETE ON account_email_delivery_events
            FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
        `,
      });
    },
  },
];
