import { type PostgresMigration } from '../postgresMigrations';

export const POSTGRES_AGENT_LIFECYCLE_MIGRATIONS: readonly PostgresMigration[] = [
  {
    id: '010_agent_versions_deployments',
    up: async (database) => {
      await database.execute({
        text: `
          CREATE TABLE IF NOT EXISTS agent_versions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL,
            agent_id INTEGER NOT NULL,
            version_number INTEGER NOT NULL,
            status TEXT NOT NULL DEFAULT 'preview',
            config_json TEXT NOT NULL,
            source_path TEXT NOT NULL DEFAULT '',
            checksum TEXT NOT NULL,
            created_by_user_id INTEGER,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            published_at TIMESTAMPTZ,
            UNIQUE(agent_id, version_number),
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(agent_id) REFERENCES agents(id) ON DELETE CASCADE,
            FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
          );

          CREATE TABLE IF NOT EXISTS agent_deployments (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL,
            agent_id INTEGER NOT NULL,
            version_id INTEGER NOT NULL,
            environment TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'active',
            trigger TEXT NOT NULL DEFAULT 'publish',
            url_path TEXT NOT NULL,
            created_by_user_id INTEGER,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            activated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            deactivated_at TIMESTAMPTZ,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(agent_id) REFERENCES agents(id) ON DELETE CASCADE,
            FOREIGN KEY(version_id) REFERENCES agent_versions(id) ON DELETE CASCADE,
            FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
          );

          ALTER TABLE agents ADD COLUMN IF NOT EXISTS preview_version_id INTEGER;
          ALTER TABLE agents ADD COLUMN IF NOT EXISTS published_version_id INTEGER;
          ALTER TABLE runs ADD COLUMN IF NOT EXISTS agent_version_id INTEGER;

          INSERT INTO agent_versions (
            workspace_id,
            agent_id,
            version_number,
            status,
            config_json,
            source_path,
            checksum,
            published_at
          )
          SELECT
            agents.workspace_id,
            agents.id,
            1,
            'published',
            agent_configs.config_json,
            agents.path,
            'legacy-import',
            CURRENT_TIMESTAMP
          FROM agents
          JOIN agent_configs ON agent_configs.agent_id = agents.id
          WHERE agents.status = 'generated'
          ON CONFLICT (agent_id, version_number) DO NOTHING;

          UPDATE agents
          SET published_version_id = agent_versions.id
          FROM agent_versions
          WHERE agent_versions.agent_id = agents.id
            AND agent_versions.version_number = 1
            AND agents.status = 'generated'
            AND agents.published_version_id IS NULL;

          INSERT INTO agent_deployments (
            workspace_id,
            agent_id,
            version_id,
            environment,
            status,
            trigger,
            url_path
          )
          SELECT
            agents.workspace_id,
            agents.id,
            agents.published_version_id,
            'production',
            'active',
            'migration',
            '/a/' || agents.slug
          FROM agents
          WHERE agents.published_version_id IS NOT NULL
            AND NOT EXISTS (
              SELECT 1
              FROM agent_deployments
              WHERE agent_deployments.agent_id = agents.id
                AND agent_deployments.environment = 'production'
            );
        `,
      });
    },
  },
  {
    id: '011_run_idempotency',
    up: async (database) => {
      await database.execute({
        text: `
          ALTER TABLE runs ADD COLUMN IF NOT EXISTS idempotency_key TEXT;
          ALTER TABLE runs ADD COLUMN IF NOT EXISTS request_hash TEXT NOT NULL DEFAULT '';
          ALTER TABLE runs ADD COLUMN IF NOT EXISTS conversation_id INTEGER;
          CREATE UNIQUE INDEX IF NOT EXISTS idx_runs_workspace_idempotency
            ON runs(workspace_id, idempotency_key)
            WHERE idempotency_key IS NOT NULL;
        `,
      });
    },
  },
  {
    id: '012_workspace_capabilities',
    up: async (database) => {
      await database.execute({
        text: `
          ALTER TABLE runs
            ADD COLUMN IF NOT EXISTS capability_snapshot_json TEXT NOT NULL DEFAULT '{}';
          CREATE TABLE IF NOT EXISTS workspace_capability_settings (
            workspace_id INTEGER NOT NULL,
            capability_key TEXT NOT NULL,
            enabled BOOLEAN NOT NULL DEFAULT TRUE,
            updated_by_user_id INTEGER,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY(workspace_id, capability_key),
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
          );
        `,
      });
    },
  },
  {
    id: '013_document_upload_metadata',
    up: async (database) => {
      await database.execute({
        text: `
          ALTER TABLE documents
            ADD COLUMN IF NOT EXISTS mime_type TEXT NOT NULL DEFAULT 'text/plain';
          ALTER TABLE documents
            ADD COLUMN IF NOT EXISTS size_bytes INTEGER NOT NULL DEFAULT 0;
        `,
      });
    },
  },
  {
    id: '014_document_vector_metadata',
    up: async (database) => {
      await database.execute({
        text: `
          ALTER TABLE document_index_entries
            ADD COLUMN IF NOT EXISTS embedding_json TEXT NOT NULL DEFAULT '[]';
          ALTER TABLE document_index_entries
            ADD COLUMN IF NOT EXISTS embedding_provider TEXT NOT NULL DEFAULT '';
          ALTER TABLE document_index_entries
            ADD COLUMN IF NOT EXISTS embedding_model TEXT NOT NULL DEFAULT '';
          ALTER TABLE document_index_entries
            ADD COLUMN IF NOT EXISTS vector_store TEXT NOT NULL DEFAULT '';
        `,
      });
    },
  },
];
