import { type PostgresMigration } from '../postgresMigrations';

export const POSTGRES_BILLING_MIGRATIONS: readonly PostgresMigration[] = [
  {
    id: '015_billing_entitlements_ledger',
    up: async (database) => {
      await database.execute({
        text: `
          CREATE TABLE IF NOT EXISTS billing_plans (
            key TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'active',
            currency TEXT NOT NULL DEFAULT 'usd',
            monthly_price_minor INTEGER NOT NULL DEFAULT 0 CHECK(monthly_price_minor >= 0),
            monthly_credit_grant INTEGER NOT NULL DEFAULT 0 CHECK(monthly_credit_grant >= 0),
            trial_credit_grant INTEGER NOT NULL DEFAULT 0 CHECK(trial_credit_grant >= 0),
            trial_days INTEGER NOT NULL DEFAULT 0 CHECK(trial_days >= 0),
            overage_enabled BOOLEAN NOT NULL DEFAULT FALSE,
            metadata_json TEXT NOT NULL DEFAULT '{}',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
          );

          CREATE TABLE IF NOT EXISTS plan_entitlements (
            plan_key TEXT NOT NULL,
            feature_key TEXT NOT NULL,
            enabled BOOLEAN NOT NULL DEFAULT TRUE,
            quantity_limit INTEGER,
            metadata_json TEXT NOT NULL DEFAULT '{}',
            PRIMARY KEY(plan_key, feature_key),
            FOREIGN KEY(plan_key) REFERENCES billing_plans(key) ON DELETE CASCADE
          );

          CREATE TABLE IF NOT EXISTS workspace_subscriptions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL UNIQUE,
            plan_key TEXT NOT NULL,
            state TEXT NOT NULL,
            period_starts_at TIMESTAMPTZ NOT NULL,
            period_ends_at TIMESTAMPTZ,
            trial_ends_at TIMESTAMPTZ,
            cancel_at_period_end BOOLEAN NOT NULL DEFAULT FALSE,
            provider TEXT NOT NULL DEFAULT '',
            provider_customer_ref TEXT NOT NULL DEFAULT '',
            provider_subscription_ref TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(plan_key) REFERENCES billing_plans(key)
          );

          CREATE TABLE IF NOT EXISTS trial_grants (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL UNIQUE,
            user_id INTEGER NOT NULL UNIQUE,
            plan_key TEXT NOT NULL,
            credit_amount INTEGER NOT NULL CHECK(credit_amount > 0),
            starts_at TIMESTAMPTZ NOT NULL,
            ends_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
            FOREIGN KEY(plan_key) REFERENCES billing_plans(key)
          );

          CREATE TABLE IF NOT EXISTS entitlement_grants (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL,
            feature_key TEXT NOT NULL,
            enabled BOOLEAN NOT NULL,
            quantity_limit INTEGER,
            source_type TEXT NOT NULL,
            source_ref TEXT NOT NULL,
            priority INTEGER NOT NULL DEFAULT 100,
            starts_at TIMESTAMPTZ NOT NULL,
            ends_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(workspace_id, source_type, source_ref, feature_key),
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
          );

          CREATE TABLE IF NOT EXISTS credit_accounts (
            workspace_id INTEGER PRIMARY KEY,
            available_credits INTEGER NOT NULL DEFAULT 0 CHECK(available_credits >= 0),
            reserved_credits INTEGER NOT NULL DEFAULT 0 CHECK(reserved_credits >= 0),
            spent_credits INTEGER NOT NULL DEFAULT 0 CHECK(spent_credits >= 0),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
          );

          CREATE TABLE IF NOT EXISTS credit_reservations (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL,
            idempotency_key TEXT NOT NULL,
            meter TEXT NOT NULL,
            reserved_credits INTEGER NOT NULL CHECK(reserved_credits > 0),
            settled_credits INTEGER,
            state TEXT NOT NULL DEFAULT 'reserved',
            usage_event_id INTEGER,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            settled_at TIMESTAMPTZ,
            released_at TIMESTAMPTZ,
            UNIQUE(workspace_id, idempotency_key),
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
          );

          CREATE TABLE IF NOT EXISTS usage_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL,
            reservation_id INTEGER NOT NULL UNIQUE,
            idempotency_key TEXT NOT NULL,
            meter TEXT NOT NULL,
            quantity INTEGER NOT NULL CHECK(quantity >= 0),
            credits_charged INTEGER NOT NULL CHECK(credits_charged >= 0),
            resource_type TEXT NOT NULL DEFAULT '',
            resource_id TEXT NOT NULL DEFAULT '',
            metadata_json TEXT NOT NULL DEFAULT '{}',
            occurred_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(workspace_id, idempotency_key),
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(reservation_id) REFERENCES credit_reservations(id)
          );

          CREATE TABLE IF NOT EXISTS credit_ledger_entries (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL,
            idempotency_key TEXT NOT NULL,
            event_type TEXT NOT NULL,
            available_delta INTEGER NOT NULL DEFAULT 0,
            reserved_delta INTEGER NOT NULL DEFAULT 0,
            spent_delta INTEGER NOT NULL DEFAULT 0,
            reservation_id INTEGER,
            usage_event_id INTEGER,
            source_type TEXT NOT NULL DEFAULT '',
            source_ref TEXT NOT NULL DEFAULT '',
            metadata_json TEXT NOT NULL DEFAULT '{}',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(workspace_id, idempotency_key),
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(reservation_id) REFERENCES credit_reservations(id),
            FOREIGN KEY(usage_event_id) REFERENCES usage_events(id)
          );

          CREATE OR REPLACE FUNCTION primalthrum_apply_credit_ledger_entry()
          RETURNS TRIGGER LANGUAGE plpgsql AS $function$
          BEGIN
            INSERT INTO credit_accounts (workspace_id)
            VALUES (NEW.workspace_id)
            ON CONFLICT (workspace_id) DO NOTHING;
            UPDATE credit_accounts
            SET available_credits = available_credits + NEW.available_delta,
                reserved_credits = reserved_credits + NEW.reserved_delta,
                spent_credits = spent_credits + NEW.spent_delta,
                updated_at = CURRENT_TIMESTAMP
            WHERE workspace_id = NEW.workspace_id;
            RETURN NEW;
          END;
          $function$;

          DROP TRIGGER IF EXISTS credit_ledger_apply ON credit_ledger_entries;
          CREATE TRIGGER credit_ledger_apply
            AFTER INSERT ON credit_ledger_entries
            FOR EACH ROW EXECUTE FUNCTION primalthrum_apply_credit_ledger_entry();

          CREATE OR REPLACE FUNCTION primalthrum_reject_immutable_mutation()
          RETURNS TRIGGER LANGUAGE plpgsql AS $function$
          BEGIN
            RAISE EXCEPTION '% rows are immutable', TG_TABLE_NAME USING ERRCODE = '55000';
          END;
          $function$;

          DROP TRIGGER IF EXISTS credit_ledger_immutable ON credit_ledger_entries;
          CREATE TRIGGER credit_ledger_immutable
            BEFORE UPDATE OR DELETE ON credit_ledger_entries
            FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();

          DROP TRIGGER IF EXISTS usage_events_immutable ON usage_events;
          CREATE TRIGGER usage_events_immutable
            BEFORE UPDATE OR DELETE ON usage_events
            FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
        `,
      });

      await database.execute({
        text: `
          INSERT INTO billing_plans (
            key, name, monthly_price_minor, monthly_credit_grant,
            trial_credit_grant, trial_days, overage_enabled, metadata_json
          ) VALUES
            ('free', 'Free', 0, 1000, 0, 0, FALSE, '{"position":1}'),
            ('pro', 'Pro', 2900, 25000, 10000, 7, TRUE, '{"position":2}'),
            ('team', 'Team', 9900, 100000, 0, 0, TRUE, '{"position":3}'),
            ('business', 'Business', 29900, 350000, 0, 0, TRUE, '{"position":4}'),
            ('enterprise', 'Enterprise', 0, 0, 0, 0, TRUE, '{"position":5,"contactSales":true}')
          ON CONFLICT (key) DO NOTHING;

          INSERT INTO plan_entitlements (plan_key, feature_key, enabled, quantity_limit) VALUES
            ('free', 'agents.create', TRUE, 2),
            ('free', 'seats', TRUE, 1),
            ('free', 'rag', TRUE, 1),
            ('free', 'voice', FALSE, 0),
            ('free', 'api', FALSE, 0),
            ('free', 'publishing', FALSE, 0),
            ('pro', 'agents.create', TRUE, 20),
            ('pro', 'seats', TRUE, 1),
            ('pro', 'rag', TRUE, NULL),
            ('pro', 'voice', TRUE, NULL),
            ('pro', 'api', TRUE, NULL),
            ('pro', 'publishing', TRUE, NULL),
            ('pro', 'source.export', TRUE, NULL),
            ('team', 'agents.create', TRUE, 100),
            ('team', 'seats', TRUE, 10),
            ('team', 'rag', TRUE, NULL),
            ('team', 'voice', TRUE, NULL),
            ('team', 'api', TRUE, NULL),
            ('team', 'publishing', TRUE, NULL),
            ('team', 'source.export', TRUE, NULL),
            ('team', 'audit', TRUE, NULL),
            ('business', 'agents.create', TRUE, 500),
            ('business', 'seats', TRUE, 50),
            ('business', 'rag', TRUE, NULL),
            ('business', 'voice', TRUE, NULL),
            ('business', 'api', TRUE, NULL),
            ('business', 'publishing', TRUE, NULL),
            ('business', 'source.export', TRUE, NULL),
            ('business', 'audit', TRUE, NULL),
            ('business', 'sso', TRUE, NULL),
            ('business', 'retention.controls', TRUE, NULL),
            ('enterprise', 'agents.create', TRUE, NULL),
            ('enterprise', 'seats', TRUE, NULL),
            ('enterprise', 'rag', TRUE, NULL),
            ('enterprise', 'voice', TRUE, NULL),
            ('enterprise', 'api', TRUE, NULL),
            ('enterprise', 'publishing', TRUE, NULL),
            ('enterprise', 'source.export', TRUE, NULL),
            ('enterprise', 'audit', TRUE, NULL),
            ('enterprise', 'sso', TRUE, NULL),
            ('enterprise', 'retention.controls', TRUE, NULL),
            ('enterprise', 'private.deployment', TRUE, NULL)
          ON CONFLICT (plan_key, feature_key) DO NOTHING;

          INSERT INTO workspace_subscriptions (workspace_id, plan_key, state, period_starts_at)
          SELECT id, 'free', 'active', CURRENT_TIMESTAMP
          FROM workspaces
          ON CONFLICT (workspace_id) DO NOTHING;

          INSERT INTO credit_accounts (workspace_id)
          SELECT id FROM workspaces
          ON CONFLICT (workspace_id) DO NOTHING;
        `,
      });
    },
  },
];
