import { type PostgresMigration } from '../postgresMigrations';

export const POSTGRES_COMPLIANCE_MIGRATIONS: readonly PostgresMigration[] = [
  {
    id: '029_document_upload_security',
    up: async (database) => {
      await database.execute({ text: `
        CREATE TABLE IF NOT EXISTS document_upload_security_events (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          event_id TEXT NOT NULL UNIQUE,
          workspace_id INTEGER NOT NULL,
          agent_id INTEGER NOT NULL,
          user_id INTEGER NOT NULL,
          filename_hash TEXT NOT NULL CHECK(length(filename_hash) = 64),
          content_sha256 TEXT NOT NULL CHECK(length(content_sha256) = 64),
          mime_type TEXT NOT NULL,
          size_bytes INTEGER NOT NULL CHECK(size_bytes > 0),
          scanner TEXT NOT NULL,
          status TEXT NOT NULL CHECK(status IN ('clean', 'rejected', 'error')),
          threat_name TEXT NOT NULL DEFAULT '',
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX IF NOT EXISTS document_upload_security_workspace_time_idx
          ON document_upload_security_events(workspace_id, created_at DESC, id DESC);
        DROP TRIGGER IF EXISTS document_upload_security_events_immutable ON document_upload_security_events;
        CREATE TRIGGER document_upload_security_events_immutable
          BEFORE UPDATE OR DELETE ON document_upload_security_events
          FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
      ` });
    },
  },
  {
    id: '030_account_privacy_rights',
    up: async (database) => {
      await database.execute({ text: `
        ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
        ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
        CREATE TABLE IF NOT EXISTS account_privacy_requests (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          request_id TEXT NOT NULL UNIQUE,
          user_id INTEGER NOT NULL,
          workspace_id INTEGER,
          request_type TEXT NOT NULL CHECK(request_type IN ('export', 'deletion')),
          scope TEXT NOT NULL CHECK(scope IN ('account', 'workspace')),
          status TEXT NOT NULL CHECK(status IN ('completed', 'scheduled', 'processing', 'cancelled', 'failed')),
          attempts INTEGER NOT NULL DEFAULT 0 CHECK(attempts >= 0),
          scheduled_for TIMESTAMPTZ,
          completed_at TIMESTAMPTZ,
          cancelled_at TIMESTAMPTZ,
          failure_reason TEXT NOT NULL DEFAULT '',
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS account_privacy_events (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          event_id TEXT NOT NULL UNIQUE,
          request_id TEXT NOT NULL,
          subject_hash TEXT NOT NULL CHECK(length(subject_hash) = 64),
          event_type TEXT NOT NULL CHECK(event_type IN (
            'export_completed', 'deletion_scheduled', 'deletion_cancelled',
            'deletion_started', 'deletion_completed', 'deletion_failed'
          )),
          metadata_json TEXT NOT NULL DEFAULT '{}',
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX IF NOT EXISTS account_privacy_requests_user_time_idx
          ON account_privacy_requests(user_id, created_at DESC, id DESC);
        CREATE INDEX IF NOT EXISTS account_privacy_requests_due_idx
          ON account_privacy_requests(status, scheduled_for, id);
        CREATE INDEX IF NOT EXISTS account_privacy_events_request_idx
          ON account_privacy_events(request_id, id);
        CREATE UNIQUE INDEX IF NOT EXISTS account_privacy_active_deletion_idx
          ON account_privacy_requests(user_id)
          WHERE request_type = 'deletion' AND status IN ('scheduled', 'processing');
        DROP TRIGGER IF EXISTS account_privacy_events_immutable ON account_privacy_events;
        CREATE TRIGGER account_privacy_events_immutable
          BEFORE UPDATE OR DELETE ON account_privacy_events
          FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
      ` });
    },
  },
  {
    id: '031_workspace_ownership_transfer',
    up: async (database) => {
      await database.execute({ text: `
        CREATE UNIQUE INDEX IF NOT EXISTS workspace_active_owner_idx
          ON workspace_memberships(workspace_id)
          WHERE role = 'owner' AND status = 'active';
        CREATE TABLE IF NOT EXISTS workspace_ownership_events (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          event_id TEXT NOT NULL UNIQUE,
          workspace_id INTEGER NOT NULL,
          previous_owner_user_id INTEGER NOT NULL,
          new_owner_user_id INTEGER NOT NULL,
          initiated_by_user_id INTEGER NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          CHECK(previous_owner_user_id <> new_owner_user_id),
          CHECK(previous_owner_user_id = initiated_by_user_id)
        );
        CREATE INDEX IF NOT EXISTS workspace_ownership_events_workspace_time_idx
          ON workspace_ownership_events(workspace_id, created_at DESC, id DESC);
        DROP TRIGGER IF EXISTS workspace_ownership_events_immutable ON workspace_ownership_events;
        CREATE TRIGGER workspace_ownership_events_immutable
          BEFORE UPDATE OR DELETE ON workspace_ownership_events
          FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
      ` });
    },
  },
  {
    id: '032_workspace_legal_holds',
    up: async (database) => {
      await database.execute({ text: `
        CREATE TABLE IF NOT EXISTS workspace_legal_holds (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          hold_ref TEXT NOT NULL UNIQUE,
          workspace_id INTEGER NOT NULL,
          external_case_ref TEXT NOT NULL UNIQUE,
          basis TEXT NOT NULL CHECK(basis IN ('litigation', 'regulatory', 'investigation', 'tax', 'contractual')),
          reason TEXT NOT NULL,
          status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'released')),
          revision INTEGER NOT NULL DEFAULT 1 CHECK(revision >= 1),
          created_by_operator_id INTEGER NOT NULL,
          released_by_operator_id INTEGER,
          release_reason TEXT NOT NULL DEFAULT '',
          released_at TIMESTAMPTZ,
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          CHECK((status = 'active' AND released_by_operator_id IS NULL
              AND release_reason = '' AND released_at IS NULL)
            OR (status = 'released' AND released_by_operator_id IS NOT NULL
              AND release_reason <> '' AND released_at IS NOT NULL
              AND released_by_operator_id <> created_by_operator_id)),
          FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE RESTRICT,
          FOREIGN KEY(created_by_operator_id) REFERENCES operator_users(id) ON DELETE RESTRICT,
          FOREIGN KEY(released_by_operator_id) REFERENCES operator_users(id) ON DELETE RESTRICT
        );
        CREATE TABLE IF NOT EXISTS workspace_legal_hold_events (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          event_id TEXT NOT NULL UNIQUE,
          legal_hold_id INTEGER NOT NULL,
          operator_user_id INTEGER NOT NULL,
          action TEXT NOT NULL CHECK(action IN ('placed', 'released')),
          revision INTEGER NOT NULL CHECK(revision >= 1),
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY(legal_hold_id) REFERENCES workspace_legal_holds(id) ON DELETE RESTRICT,
          FOREIGN KEY(operator_user_id) REFERENCES operator_users(id) ON DELETE RESTRICT
        );
        CREATE INDEX IF NOT EXISTS workspace_legal_holds_workspace_status_idx
          ON workspace_legal_holds(workspace_id, status, created_at DESC, id DESC);
        CREATE INDEX IF NOT EXISTS workspace_legal_hold_events_hold_time_idx
          ON workspace_legal_hold_events(legal_hold_id, created_at ASC, id ASC);

        CREATE OR REPLACE FUNCTION primalthrum_guard_legal_hold_update()
        RETURNS TRIGGER LANGUAGE plpgsql AS $function$
        BEGIN
          IF NEW.id IS DISTINCT FROM OLD.id OR NEW.hold_ref IS DISTINCT FROM OLD.hold_ref
            OR NEW.workspace_id IS DISTINCT FROM OLD.workspace_id
            OR NEW.external_case_ref IS DISTINCT FROM OLD.external_case_ref
            OR NEW.basis IS DISTINCT FROM OLD.basis OR NEW.reason IS DISTINCT FROM OLD.reason
            OR NEW.created_by_operator_id IS DISTINCT FROM OLD.created_by_operator_id
            OR NEW.created_at IS DISTINCT FROM OLD.created_at OR OLD.status <> 'active'
            OR NEW.status <> 'released' OR NEW.revision <> OLD.revision + 1
            OR NEW.released_by_operator_id IS NULL
            OR NEW.released_by_operator_id = OLD.created_by_operator_id
            OR NEW.release_reason = '' OR NEW.released_at IS NULL THEN
            RAISE EXCEPTION 'workspace legal hold transition is invalid' USING ERRCODE = '55000';
          END IF;
          RETURN NEW;
        END;
        $function$;
        DROP TRIGGER IF EXISTS workspace_legal_holds_no_delete ON workspace_legal_holds;
        CREATE TRIGGER workspace_legal_holds_no_delete BEFORE DELETE ON workspace_legal_holds
          FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
        DROP TRIGGER IF EXISTS workspace_legal_holds_update_guard ON workspace_legal_holds;
        CREATE TRIGGER workspace_legal_holds_update_guard BEFORE UPDATE ON workspace_legal_holds
          FOR EACH ROW EXECUTE FUNCTION primalthrum_guard_legal_hold_update();
        DROP TRIGGER IF EXISTS workspace_legal_hold_events_immutable ON workspace_legal_hold_events;
        CREATE TRIGGER workspace_legal_hold_events_immutable
          BEFORE UPDATE OR DELETE ON workspace_legal_hold_events
          FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();

        ALTER TABLE retention_events DROP CONSTRAINT IF EXISTS retention_events_event_type_check;
        ALTER TABLE retention_events ADD CONSTRAINT retention_events_event_type_check
          CHECK(event_type IN ('policy_updated', 'enforcement_completed', 'enforcement_blocked'));
      ` });
    },
  },
];
