import { type PostgresMigration } from '../postgresMigrations';
import { DEFAULT_WORKSPACE_ID } from '../workspaceDefaults';

export const POSTGRES_IDENTITY_MIGRATIONS: readonly PostgresMigration[] = [
  {
    id: '002_admin_sessions',
    up: async (database) => {
      await database.execute({
        text: `
          CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL DEFAULT ${DEFAULT_WORKSPACE_ID},
            email TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
          );

          CREATE TABLE IF NOT EXISTS sessions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            workspace_id INTEGER NOT NULL DEFAULT ${DEFAULT_WORKSPACE_ID},
            token_hash TEXT NOT NULL UNIQUE,
            expires_at TIMESTAMPTZ NOT NULL,
            revoked_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
          );
        `,
      });
    },
  },
  {
    id: '003_secret_references',
    up: async (database) => {
      await database.execute({
        text: `
          CREATE TABLE IF NOT EXISTS secrets (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL DEFAULT ${DEFAULT_WORKSPACE_ID},
            secret_ref TEXT NOT NULL UNIQUE,
            ciphertext TEXT NOT NULL,
            iv TEXT NOT NULL,
            auth_tag TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
          );
        `,
      });
    },
  },
];
