import { type PostgresMigration } from '../postgresMigrations';
import { DEFAULT_WORKSPACE_ID } from '../workspaceDefaults';

export const POSTGRES_KNOWLEDGE_MIGRATIONS: readonly PostgresMigration[] = [
  {
    id: '006_document_storage_refs',
    up: async (database) => {
      await database.execute({
        text: "ALTER TABLE documents ADD COLUMN IF NOT EXISTS storage_ref TEXT NOT NULL DEFAULT '';",
      });
    },
  },
  {
    id: '007_document_index_entries',
    up: async (database) => {
      await database.execute({
        text: `
          CREATE TABLE IF NOT EXISTS document_index_entries (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL DEFAULT ${DEFAULT_WORKSPACE_ID},
            agent_id INTEGER NOT NULL,
            document_id INTEGER NOT NULL,
            chunk_id TEXT NOT NULL,
            text TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(document_id, chunk_id),
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(agent_id) REFERENCES agents(id) ON DELETE CASCADE,
            FOREIGN KEY(document_id) REFERENCES documents(id) ON DELETE CASCADE
          );
        `,
      });
    },
  },
  {
    id: '008_conversations',
    up: async (database) => {
      await database.execute({
        text: `
          CREATE TABLE IF NOT EXISTS conversations (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL DEFAULT ${DEFAULT_WORKSPACE_ID},
            agent_id INTEGER NOT NULL,
            title TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(agent_id) REFERENCES agents(id) ON DELETE CASCADE
          );

          CREATE TABLE IF NOT EXISTS conversation_messages (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL DEFAULT ${DEFAULT_WORKSPACE_ID},
            conversation_id INTEGER NOT NULL,
            role TEXT NOT NULL,
            content TEXT NOT NULL,
            sources_json TEXT NOT NULL DEFAULT '[]',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(conversation_id) REFERENCES conversations(id) ON DELETE CASCADE
          );
        `,
      });
    },
  },
];
