import { type PostgresMigration } from '../postgresMigrations';
import { DEFAULT_WORKSPACE_ID } from '../workspaceDefaults';

export const POSTGRES_OPERATIONS_MIGRATIONS: readonly PostgresMigration[] = [
  {
    id: '004_tool_audit_logs',
    up: async (database) => {
      await database.execute({
        text: `
          CREATE TABLE IF NOT EXISTS tool_audit_logs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL DEFAULT ${DEFAULT_WORKSPACE_ID},
            run_id INTEGER NOT NULL,
            event_id INTEGER NOT NULL UNIQUE,
            tool_name TEXT NOT NULL,
            status TEXT NOT NULL,
            dangerous BOOLEAN NOT NULL DEFAULT FALSE,
            node TEXT NOT NULL DEFAULT '',
            payload_json TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(run_id) REFERENCES runs(id) ON DELETE CASCADE,
            FOREIGN KEY(event_id) REFERENCES stream_events(id) ON DELETE CASCADE
          );
        `,
      });
    },
  },
  {
    id: '005_background_jobs',
    up: async (database) => {
      await database.execute({
        text: `
          CREATE TABLE IF NOT EXISTS jobs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL DEFAULT ${DEFAULT_WORKSPACE_ID},
            type TEXT NOT NULL,
            status TEXT NOT NULL,
            attempts INTEGER NOT NULL DEFAULT 0,
            max_attempts INTEGER NOT NULL DEFAULT 3,
            payload_json TEXT NOT NULL,
            result_json TEXT NOT NULL DEFAULT '{}',
            error TEXT NOT NULL DEFAULT '',
            run_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            started_at TIMESTAMPTZ,
            completed_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
          );
        `,
      });
    },
  },
];
