import { type PostgresMigration } from '../postgresMigrations';

export const POSTGRES_OPERATOR_MIGRATIONS: readonly PostgresMigration[] = [
  {
    id: '027_operator_control_plane',
    up: async (database) => {
      await database.execute({ text: `
        CREATE TABLE IF NOT EXISTS operator_users (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          email TEXT NOT NULL UNIQUE,
          password_hash TEXT NOT NULL,
          role TEXT NOT NULL CHECK(role IN ('super_admin', 'support', 'billing', 'security', 'viewer')),
          status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'disabled')),
          must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
          bootstrap_root BOOLEAN NOT NULL DEFAULT FALSE,
          last_login_at TIMESTAMPTZ,
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS operator_sessions (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          operator_user_id INTEGER NOT NULL,
          token_hash TEXT NOT NULL UNIQUE,
          expires_at TIMESTAMPTZ NOT NULL,
          revoked_at TIMESTAMPTZ,
          last_seen_at TIMESTAMPTZ,
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY(operator_user_id) REFERENCES operator_users(id) ON DELETE CASCADE
        );
        CREATE TABLE IF NOT EXISTS operator_support_grants (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          workspace_id INTEGER NOT NULL,
          operator_user_id INTEGER NOT NULL,
          permissions_json TEXT NOT NULL,
          reason TEXT NOT NULL,
          ticket_ref TEXT NOT NULL,
          expires_at TIMESTAMPTZ NOT NULL,
          revoked_at TIMESTAMPTZ,
          revoked_by_operator_id INTEGER,
          created_by_operator_id INTEGER NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY(operator_user_id) REFERENCES operator_users(id) ON DELETE RESTRICT,
          FOREIGN KEY(revoked_by_operator_id) REFERENCES operator_users(id) ON DELETE RESTRICT,
          FOREIGN KEY(created_by_operator_id) REFERENCES operator_users(id) ON DELETE RESTRICT
        );
        CREATE TABLE IF NOT EXISTS operator_audit_events (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          event_id TEXT NOT NULL UNIQUE,
          operator_user_id INTEGER,
          event_type TEXT NOT NULL,
          target_type TEXT NOT NULL DEFAULT '',
          target_id TEXT NOT NULL DEFAULT '',
          metadata_json TEXT NOT NULL DEFAULT '{}',
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY(operator_user_id) REFERENCES operator_users(id) ON DELETE RESTRICT
        );
        CREATE INDEX IF NOT EXISTS operator_sessions_active_idx
          ON operator_sessions(token_hash, expires_at, revoked_at);
        CREATE UNIQUE INDEX IF NOT EXISTS operator_bootstrap_root_once_idx
          ON operator_users(bootstrap_root) WHERE bootstrap_root = TRUE;
        CREATE INDEX IF NOT EXISTS operator_support_grants_active_idx
          ON operator_support_grants(operator_user_id, workspace_id, expires_at, revoked_at);
        CREATE INDEX IF NOT EXISTS operator_audit_events_time_idx
          ON operator_audit_events(created_at DESC, id DESC);

        DROP TRIGGER IF EXISTS operator_audit_events_immutable ON operator_audit_events;
        CREATE TRIGGER operator_audit_events_immutable
          BEFORE UPDATE OR DELETE ON operator_audit_events
          FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
        DROP TRIGGER IF EXISTS operator_support_grants_no_delete ON operator_support_grants;
        CREATE TRIGGER operator_support_grants_no_delete
          BEFORE DELETE ON operator_support_grants
          FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();

        CREATE OR REPLACE FUNCTION primalthrum_guard_support_grant_update()
        RETURNS TRIGGER LANGUAGE plpgsql AS $function$
        BEGIN
          IF NEW.id IS DISTINCT FROM OLD.id
            OR NEW.workspace_id IS DISTINCT FROM OLD.workspace_id
            OR NEW.operator_user_id IS DISTINCT FROM OLD.operator_user_id
            OR NEW.permissions_json IS DISTINCT FROM OLD.permissions_json
            OR NEW.reason IS DISTINCT FROM OLD.reason
            OR NEW.ticket_ref IS DISTINCT FROM OLD.ticket_ref
            OR NEW.expires_at IS DISTINCT FROM OLD.expires_at
            OR NEW.created_by_operator_id IS DISTINCT FROM OLD.created_by_operator_id
            OR NEW.created_at IS DISTINCT FROM OLD.created_at
            OR OLD.revoked_at IS NOT NULL OR NEW.revoked_at IS NULL
            OR NEW.revoked_by_operator_id IS NULL THEN
            RAISE EXCEPTION 'operator support grant fields are immutable' USING ERRCODE = '55000';
          END IF;
          RETURN NEW;
        END;
        $function$;
        DROP TRIGGER IF EXISTS operator_support_grants_update_guard ON operator_support_grants;
        CREATE TRIGGER operator_support_grants_update_guard
          BEFORE UPDATE ON operator_support_grants
          FOR EACH ROW EXECUTE FUNCTION primalthrum_guard_support_grant_update();
      ` });
    },
  },
  {
    id: '028_operator_change_control',
    up: async (database) => {
      await database.execute({ text: `
        CREATE TABLE IF NOT EXISTS operator_feature_flags (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          key TEXT NOT NULL UNIQUE,
          description TEXT NOT NULL,
          enabled BOOLEAN NOT NULL DEFAULT FALSE,
          kill_switch BOOLEAN NOT NULL DEFAULT FALSE,
          rollout_percentage INTEGER NOT NULL DEFAULT 0 CHECK(rollout_percentage BETWEEN 0 AND 100),
          revision INTEGER NOT NULL DEFAULT 1 CHECK(revision >= 1),
          created_by_operator_id INTEGER NOT NULL,
          updated_by_operator_id INTEGER NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY(created_by_operator_id) REFERENCES operator_users(id) ON DELETE RESTRICT,
          FOREIGN KEY(updated_by_operator_id) REFERENCES operator_users(id) ON DELETE RESTRICT
        );
        CREATE TABLE IF NOT EXISTS operator_feature_flag_overrides (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          feature_flag_id INTEGER NOT NULL,
          workspace_id INTEGER NOT NULL,
          enabled BOOLEAN NOT NULL,
          reason TEXT NOT NULL,
          active BOOLEAN NOT NULL DEFAULT TRUE,
          revision INTEGER NOT NULL DEFAULT 1 CHECK(revision >= 1),
          created_by_operator_id INTEGER NOT NULL,
          updated_by_operator_id INTEGER NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY(feature_flag_id) REFERENCES operator_feature_flags(id) ON DELETE RESTRICT,
          FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE RESTRICT,
          FOREIGN KEY(created_by_operator_id) REFERENCES operator_users(id) ON DELETE RESTRICT,
          FOREIGN KEY(updated_by_operator_id) REFERENCES operator_users(id) ON DELETE RESTRICT
        );
        CREATE TABLE IF NOT EXISTS operator_feature_flag_events (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          event_id TEXT NOT NULL UNIQUE,
          feature_flag_id INTEGER NOT NULL,
          operator_user_id INTEGER NOT NULL,
          action TEXT NOT NULL CHECK(action IN ('created', 'updated', 'override_created', 'override_revoked')),
          snapshot_json TEXT NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY(feature_flag_id) REFERENCES operator_feature_flags(id) ON DELETE RESTRICT,
          FOREIGN KEY(operator_user_id) REFERENCES operator_users(id) ON DELETE RESTRICT
        );
        CREATE TABLE IF NOT EXISTS operator_incidents (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          incident_ref TEXT NOT NULL UNIQUE,
          title TEXT NOT NULL,
          severity TEXT NOT NULL CHECK(severity IN ('sev1', 'sev2', 'sev3', 'sev4')),
          status TEXT NOT NULL CHECK(status IN ('investigating', 'identified', 'monitoring', 'resolved')),
          impact_scope TEXT NOT NULL CHECK(impact_scope IN ('platform', 'multi_workspace', 'workspace')),
          workspace_id INTEGER,
          summary TEXT NOT NULL,
          started_at TIMESTAMPTZ NOT NULL,
          resolved_at TIMESTAMPTZ,
          owner_operator_id INTEGER,
          revision INTEGER NOT NULL DEFAULT 1 CHECK(revision >= 1),
          created_by_operator_id INTEGER NOT NULL,
          updated_by_operator_id INTEGER NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          CHECK((impact_scope = 'workspace' AND workspace_id IS NOT NULL)
            OR (impact_scope <> 'workspace' AND workspace_id IS NULL)),
          CHECK((status = 'resolved' AND resolved_at IS NOT NULL)
            OR (status <> 'resolved' AND resolved_at IS NULL)),
          FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE RESTRICT,
          FOREIGN KEY(owner_operator_id) REFERENCES operator_users(id) ON DELETE RESTRICT,
          FOREIGN KEY(created_by_operator_id) REFERENCES operator_users(id) ON DELETE RESTRICT,
          FOREIGN KEY(updated_by_operator_id) REFERENCES operator_users(id) ON DELETE RESTRICT
        );
        CREATE TABLE IF NOT EXISTS operator_incident_events (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          event_id TEXT NOT NULL UNIQUE,
          incident_id INTEGER NOT NULL,
          operator_user_id INTEGER NOT NULL,
          event_type TEXT NOT NULL CHECK(event_type IN (
            'created', 'updated', 'status_changed', 'note', 'mitigation', 'customer_update'
          )),
          message TEXT NOT NULL,
          from_status TEXT NOT NULL DEFAULT '',
          to_status TEXT NOT NULL DEFAULT '',
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY(incident_id) REFERENCES operator_incidents(id) ON DELETE RESTRICT,
          FOREIGN KEY(operator_user_id) REFERENCES operator_users(id) ON DELETE RESTRICT
        );
        CREATE UNIQUE INDEX IF NOT EXISTS operator_flag_active_workspace_override_idx
          ON operator_feature_flag_overrides(feature_flag_id, workspace_id) WHERE active = TRUE;
        CREATE INDEX IF NOT EXISTS operator_feature_flag_events_time_idx
          ON operator_feature_flag_events(feature_flag_id, created_at DESC, id DESC);
        CREATE INDEX IF NOT EXISTS operator_incidents_status_time_idx
          ON operator_incidents(status, severity, started_at DESC);
        CREATE INDEX IF NOT EXISTS operator_incident_events_time_idx
          ON operator_incident_events(incident_id, created_at ASC, id ASC);

        CREATE OR REPLACE FUNCTION primalthrum_guard_feature_flag_update()
        RETURNS TRIGGER LANGUAGE plpgsql AS $function$
        BEGIN
          IF NEW.id IS DISTINCT FROM OLD.id OR NEW.key IS DISTINCT FROM OLD.key
            OR NEW.created_by_operator_id IS DISTINCT FROM OLD.created_by_operator_id
            OR NEW.created_at IS DISTINCT FROM OLD.created_at
            OR NEW.revision <> OLD.revision + 1 THEN
            RAISE EXCEPTION 'operator feature flag revision is invalid' USING ERRCODE = '55000';
          END IF;
          RETURN NEW;
        END;
        $function$;
        CREATE OR REPLACE FUNCTION primalthrum_guard_feature_flag_override_update()
        RETURNS TRIGGER LANGUAGE plpgsql AS $function$
        BEGIN
          IF NEW.id IS DISTINCT FROM OLD.id
            OR NEW.feature_flag_id IS DISTINCT FROM OLD.feature_flag_id
            OR NEW.workspace_id IS DISTINCT FROM OLD.workspace_id
            OR NEW.enabled IS DISTINCT FROM OLD.enabled OR NEW.reason IS DISTINCT FROM OLD.reason
            OR NEW.created_by_operator_id IS DISTINCT FROM OLD.created_by_operator_id
            OR NEW.created_at IS DISTINCT FROM OLD.created_at
            OR OLD.active IS DISTINCT FROM TRUE OR NEW.active IS DISTINCT FROM FALSE
            OR NEW.revision <> OLD.revision + 1 THEN
            RAISE EXCEPTION 'operator feature flag override is immutable' USING ERRCODE = '55000';
          END IF;
          RETURN NEW;
        END;
        $function$;
        CREATE OR REPLACE FUNCTION primalthrum_guard_incident_update()
        RETURNS TRIGGER LANGUAGE plpgsql AS $function$
        BEGIN
          IF NEW.id IS DISTINCT FROM OLD.id OR NEW.incident_ref IS DISTINCT FROM OLD.incident_ref
            OR NEW.started_at IS DISTINCT FROM OLD.started_at
            OR NEW.created_by_operator_id IS DISTINCT FROM OLD.created_by_operator_id
            OR NEW.created_at IS DISTINCT FROM OLD.created_at
            OR NEW.revision <> OLD.revision + 1 THEN
            RAISE EXCEPTION 'operator incident revision is invalid' USING ERRCODE = '55000';
          END IF;
          RETURN NEW;
        END;
        $function$;

        DROP TRIGGER IF EXISTS operator_feature_flags_no_delete ON operator_feature_flags;
        CREATE TRIGGER operator_feature_flags_no_delete BEFORE DELETE ON operator_feature_flags
          FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
        DROP TRIGGER IF EXISTS operator_feature_flags_update_guard ON operator_feature_flags;
        CREATE TRIGGER operator_feature_flags_update_guard BEFORE UPDATE ON operator_feature_flags
          FOR EACH ROW EXECUTE FUNCTION primalthrum_guard_feature_flag_update();
        DROP TRIGGER IF EXISTS operator_feature_flag_overrides_no_delete ON operator_feature_flag_overrides;
        CREATE TRIGGER operator_feature_flag_overrides_no_delete BEFORE DELETE ON operator_feature_flag_overrides
          FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
        DROP TRIGGER IF EXISTS operator_feature_flag_overrides_update_guard ON operator_feature_flag_overrides;
        CREATE TRIGGER operator_feature_flag_overrides_update_guard BEFORE UPDATE ON operator_feature_flag_overrides
          FOR EACH ROW EXECUTE FUNCTION primalthrum_guard_feature_flag_override_update();
        DROP TRIGGER IF EXISTS operator_feature_flag_events_immutable ON operator_feature_flag_events;
        CREATE TRIGGER operator_feature_flag_events_immutable BEFORE UPDATE OR DELETE ON operator_feature_flag_events
          FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
        DROP TRIGGER IF EXISTS operator_incidents_no_delete ON operator_incidents;
        CREATE TRIGGER operator_incidents_no_delete BEFORE DELETE ON operator_incidents
          FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
        DROP TRIGGER IF EXISTS operator_incidents_update_guard ON operator_incidents;
        CREATE TRIGGER operator_incidents_update_guard BEFORE UPDATE ON operator_incidents
          FOR EACH ROW EXECUTE FUNCTION primalthrum_guard_incident_update();
        DROP TRIGGER IF EXISTS operator_incident_events_immutable ON operator_incident_events;
        CREATE TRIGGER operator_incident_events_immutable BEFORE UPDATE OR DELETE ON operator_incident_events
          FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
      ` });
    },
  },
];
