import { type PostgresMigration } from '../postgresMigrations';

export const POSTGRES_PAYMENT_MIGRATIONS: readonly PostgresMigration[] = [
  {
    id: '016_payment_lifecycle',
    up: async (database) => {
      await database.execute({
        text: `
          ALTER TABLE workspace_subscriptions ADD COLUMN IF NOT EXISTS provider_price_ref TEXT NOT NULL DEFAULT '';
          ALTER TABLE workspace_subscriptions ADD COLUMN IF NOT EXISTS provider_subscription_item_ref TEXT NOT NULL DEFAULT '';
          ALTER TABLE workspace_subscriptions ADD COLUMN IF NOT EXISTS pending_plan_key TEXT NOT NULL DEFAULT '';
          ALTER TABLE workspace_subscriptions ADD COLUMN IF NOT EXISTS grace_ends_at TIMESTAMPTZ;
          ALTER TABLE workspace_subscriptions ADD COLUMN IF NOT EXISTS canceled_at TIMESTAMPTZ;
          ALTER TABLE workspace_subscriptions ADD COLUMN IF NOT EXISTS latest_provider_event_created INTEGER NOT NULL DEFAULT 0;
          ALTER TABLE workspace_subscriptions ADD COLUMN IF NOT EXISTS latest_provider_event_ref TEXT NOT NULL DEFAULT '';

          CREATE TABLE IF NOT EXISTS payment_prices (
            provider TEXT NOT NULL,
            plan_key TEXT NOT NULL,
            provider_price_ref TEXT NOT NULL,
            active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY(provider, plan_key),
            UNIQUE(provider, provider_price_ref),
            FOREIGN KEY(plan_key) REFERENCES billing_plans(key) ON DELETE CASCADE
          );

          CREATE TABLE IF NOT EXISTS payment_customers (
            workspace_id INTEGER NOT NULL,
            provider TEXT NOT NULL,
            provider_customer_ref TEXT NOT NULL,
            email TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY(workspace_id, provider),
            UNIQUE(provider, provider_customer_ref),
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
          );

          CREATE TABLE IF NOT EXISTS payment_checkout_sessions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL,
            provider TEXT NOT NULL,
            idempotency_key TEXT NOT NULL,
            provider_session_ref TEXT NOT NULL,
            plan_key TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'open',
            checkout_url TEXT NOT NULL DEFAULT '',
            created_by_user_id INTEGER NOT NULL,
            expires_at TIMESTAMPTZ,
            completed_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(workspace_id, provider, idempotency_key),
            UNIQUE(provider, provider_session_ref),
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
            FOREIGN KEY(plan_key) REFERENCES billing_plans(key)
          );

          CREATE TABLE IF NOT EXISTS payment_webhook_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            provider TEXT NOT NULL,
            provider_event_ref TEXT NOT NULL,
            event_type TEXT NOT NULL,
            livemode BOOLEAN NOT NULL DEFAULT FALSE,
            api_version TEXT NOT NULL DEFAULT '',
            payload_json TEXT NOT NULL,
            signature_timestamp INTEGER,
            object_created_at INTEGER NOT NULL DEFAULT 0,
            workspace_id INTEGER,
            status TEXT NOT NULL DEFAULT 'received',
            attempts INTEGER NOT NULL DEFAULT 1,
            error TEXT NOT NULL DEFAULT '',
            received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            processed_at TIMESTAMPTZ,
            UNIQUE(provider, provider_event_ref),
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE SET NULL
          );

          CREATE TABLE IF NOT EXISTS billing_invoices (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL,
            provider TEXT NOT NULL,
            provider_invoice_ref TEXT NOT NULL,
            provider_customer_ref TEXT NOT NULL DEFAULT '',
            provider_subscription_ref TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL,
            currency TEXT NOT NULL DEFAULT 'usd',
            amount_due_minor INTEGER NOT NULL DEFAULT 0,
            amount_paid_minor INTEGER NOT NULL DEFAULT 0,
            amount_refunded_minor INTEGER NOT NULL DEFAULT 0,
            period_starts_at TIMESTAMPTZ,
            period_ends_at TIMESTAMPTZ,
            hosted_invoice_url TEXT NOT NULL DEFAULT '',
            invoice_pdf_url TEXT NOT NULL DEFAULT '',
            due_at TIMESTAMPTZ,
            paid_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(provider, provider_invoice_ref),
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
          );

          CREATE TABLE IF NOT EXISTS billing_refunds (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL,
            provider TEXT NOT NULL,
            provider_refund_ref TEXT NOT NULL,
            provider_payment_ref TEXT NOT NULL DEFAULT '',
            provider_invoice_ref TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL,
            amount_minor INTEGER NOT NULL DEFAULT 0,
            currency TEXT NOT NULL DEFAULT 'usd',
            reason TEXT NOT NULL DEFAULT '',
            provider_created_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(provider, provider_refund_ref),
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
          );

          CREATE TABLE IF NOT EXISTS subscription_state_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL,
            provider TEXT NOT NULL,
            provider_event_ref TEXT NOT NULL,
            from_state TEXT NOT NULL,
            to_state TEXT NOT NULL,
            plan_key TEXT NOT NULL,
            effective_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(provider, provider_event_ref),
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(plan_key) REFERENCES billing_plans(key)
          );

          CREATE INDEX IF NOT EXISTS payment_webhook_events_status_idx
            ON payment_webhook_events(status, received_at);
          CREATE INDEX IF NOT EXISTS billing_invoices_workspace_idx
            ON billing_invoices(workspace_id, created_at DESC);
          CREATE INDEX IF NOT EXISTS billing_refunds_workspace_idx
            ON billing_refunds(workspace_id, created_at DESC);
        `,
      });
    },
  },
];
