import { type PostgresMigration } from '../postgresMigrations';

export const POSTGRES_PRIVACY_MIGRATIONS: readonly PostgresMigration[] = [
  {
    id: '020_privacy_consent_analytics',
    up: async (database) => {
      await database.execute({
        text: `
          CREATE TABLE IF NOT EXISTS privacy_consent_receipts (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            receipt_id TEXT NOT NULL UNIQUE,
            subject_hash TEXT NOT NULL,
            policy_version TEXT NOT NULL,
            necessary_granted BOOLEAN NOT NULL DEFAULT TRUE CHECK(necessary_granted = TRUE),
            analytics_granted BOOLEAN NOT NULL,
            action TEXT NOT NULL CHECK(action IN ('granted', 'denied', 'withdrawn')),
            source TEXT NOT NULL CHECK(source IN ('banner', 'preferences')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
          );

          CREATE TABLE IF NOT EXISTS product_analytics_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            event_id TEXT NOT NULL UNIQUE,
            consent_receipt_id INTEGER NOT NULL,
            subject_hash TEXT NOT NULL,
            event_name TEXT NOT NULL,
            path TEXT NOT NULL,
            properties_json TEXT NOT NULL DEFAULT '{}',
            occurred_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(consent_receipt_id) REFERENCES privacy_consent_receipts(id) ON DELETE RESTRICT
          );

          CREATE INDEX IF NOT EXISTS privacy_consent_subject_idx
            ON privacy_consent_receipts(subject_hash, id DESC);
          CREATE INDEX IF NOT EXISTS product_analytics_name_time_idx
            ON product_analytics_events(event_name, occurred_at);

          DROP TRIGGER IF EXISTS privacy_consent_receipts_immutable ON privacy_consent_receipts;
          CREATE TRIGGER privacy_consent_receipts_immutable
            BEFORE UPDATE OR DELETE ON privacy_consent_receipts
            FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
          DROP TRIGGER IF EXISTS product_analytics_events_immutable ON product_analytics_events;
          CREATE TRIGGER product_analytics_events_immutable
            BEFORE UPDATE OR DELETE ON product_analytics_events
            FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
        `,
      });
    },
  },
];
