import { type PostgresMigration } from '../postgresMigrations';

export const POSTGRES_RETENTION_MIGRATIONS: readonly PostgresMigration[] = [
  {
    id: '024_workspace_retention',
    up: async (database) => {
      await database.execute({
        text: `
          CREATE TABLE IF NOT EXISTS workspace_retention_policies (
            workspace_id INTEGER PRIMARY KEY,
            conversation_days INTEGER CHECK(conversation_days IS NULL OR conversation_days BETWEEN 30 AND 3650),
            run_days INTEGER CHECK(run_days IS NULL OR run_days BETWEEN 7 AND 3650),
            document_days INTEGER CHECK(document_days IS NULL OR document_days BETWEEN 30 AND 3650),
            updated_by_user_id INTEGER,
            last_enforced_at TIMESTAMPTZ,
            next_enforcement_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
          );
          CREATE TABLE IF NOT EXISTS retention_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL,
            event_type TEXT NOT NULL CHECK(event_type IN ('policy_updated', 'enforcement_completed')),
            actor_user_id INTEGER,
            policy_json TEXT NOT NULL,
            result_json TEXT NOT NULL DEFAULT '{}',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL
          );
          CREATE TABLE IF NOT EXISTS retention_file_deletions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL,
            storage_ref TEXT NOT NULL UNIQUE,
            status TEXT NOT NULL DEFAULT 'pending'
              CHECK(status IN ('pending', 'retrying', 'completed', 'failed')),
            attempts INTEGER NOT NULL DEFAULT 0,
            error TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            completed_at TIMESTAMPTZ,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
          );
          CREATE TABLE IF NOT EXISTS retained_tool_audit_logs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            original_audit_id INTEGER NOT NULL UNIQUE,
            workspace_id INTEGER NOT NULL,
            run_id INTEGER NOT NULL,
            event_id INTEGER NOT NULL UNIQUE,
            tool_name TEXT NOT NULL,
            status TEXT NOT NULL,
            dangerous BOOLEAN NOT NULL DEFAULT FALSE,
            node TEXT NOT NULL DEFAULT '',
            payload_json TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL,
            archived_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
          );
          CREATE INDEX IF NOT EXISTS workspace_retention_due_idx
            ON workspace_retention_policies(next_enforcement_at);
          CREATE INDEX IF NOT EXISTS retention_events_workspace_time_idx
            ON retention_events(workspace_id, created_at DESC);
          CREATE INDEX IF NOT EXISTS retention_file_deletions_status_idx
            ON retention_file_deletions(status, id);
          CREATE INDEX IF NOT EXISTS retained_tool_audit_workspace_run_idx
            ON retained_tool_audit_logs(workspace_id, run_id, id);
          DROP TRIGGER IF EXISTS retention_events_immutable ON retention_events;
          CREATE TRIGGER retention_events_immutable
            BEFORE UPDATE OR DELETE ON retention_events
            FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
          DROP TRIGGER IF EXISTS retained_tool_audit_logs_immutable ON retained_tool_audit_logs;
          CREATE TRIGGER retained_tool_audit_logs_immutable
            BEFORE UPDATE OR DELETE ON retained_tool_audit_logs
            FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
        `,
      });
    },
  },
];
