import { type PostgresMigration } from '../postgresMigrations';

export const POSTGRES_ABUSE_MIGRATIONS: readonly PostgresMigration[] = [
  {
    id: '022_abuse_protection',
    up: async (database) => {
      await database.execute({
        text: `
          CREATE TABLE IF NOT EXISTS abuse_rate_limit_buckets (
            rule_key TEXT NOT NULL,
            subject_hash TEXT NOT NULL,
            window_started_at TIMESTAMPTZ NOT NULL,
            window_ends_at TIMESTAMPTZ NOT NULL,
            request_count INTEGER NOT NULL DEFAULT 0 CHECK(request_count >= 0),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY(rule_key, subject_hash, window_started_at)
          );
          CREATE TABLE IF NOT EXISTS abuse_enforcement_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            event_id TEXT NOT NULL UNIQUE,
            rule_key TEXT NOT NULL,
            action TEXT NOT NULL,
            subject_hash TEXT NOT NULL,
            outcome TEXT NOT NULL CHECK(outcome IN ('rate_limited', 'challenge_failed')),
            retry_after_seconds INTEGER NOT NULL DEFAULT 0 CHECK(retry_after_seconds >= 0),
            metadata_json TEXT NOT NULL DEFAULT '{}',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
          );
          CREATE TABLE IF NOT EXISTS abuse_challenge_grants (
            grant_hash TEXT PRIMARY KEY,
            rule_key TEXT NOT NULL,
            subject_hash TEXT NOT NULL,
            expires_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
          );
          CREATE INDEX IF NOT EXISTS abuse_rate_limit_expiry_idx
            ON abuse_rate_limit_buckets(window_ends_at);
          CREATE INDEX IF NOT EXISTS abuse_enforcement_rule_time_idx
            ON abuse_enforcement_events(rule_key, created_at);
          CREATE INDEX IF NOT EXISTS abuse_challenge_grant_expiry_idx
            ON abuse_challenge_grants(expires_at);
          DROP TRIGGER IF EXISTS abuse_enforcement_events_immutable ON abuse_enforcement_events;
          CREATE TRIGGER abuse_enforcement_events_immutable
            BEFORE UPDATE OR DELETE ON abuse_enforcement_events
            FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
        `,
      });
    },
  },
];

export const POSTGRES_API_KEY_MIGRATIONS: readonly PostgresMigration[] = [
  {
    id: '023_api_keys_security',
    up: async (database) => {
      await database.execute({
        text: `
          ALTER TABLE sessions ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;
          UPDATE sessions SET last_seen_at = COALESCE(last_seen_at, created_at);

          CREATE TABLE IF NOT EXISTS workspace_api_keys (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            key_prefix TEXT NOT NULL UNIQUE,
            token_hash TEXT NOT NULL UNIQUE,
            scopes_json TEXT NOT NULL,
            created_by_user_id INTEGER,
            expires_at TIMESTAMPTZ NOT NULL,
            last_used_at TIMESTAMPTZ,
            last_used_method TEXT NOT NULL DEFAULT '',
            last_used_path TEXT NOT NULL DEFAULT '',
            revoked_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
          );
          CREATE TABLE IF NOT EXISTS api_key_usage_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            api_key_id INTEGER NOT NULL,
            workspace_id INTEGER NOT NULL,
            method TEXT NOT NULL,
            path TEXT NOT NULL,
            used_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(api_key_id) REFERENCES workspace_api_keys(id) ON DELETE RESTRICT,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
          );
          CREATE INDEX IF NOT EXISTS workspace_api_keys_active_idx
            ON workspace_api_keys(workspace_id, revoked_at, expires_at);
          CREATE INDEX IF NOT EXISTS api_key_usage_events_key_time_idx
            ON api_key_usage_events(api_key_id, used_at DESC);
          DROP TRIGGER IF EXISTS api_key_usage_events_immutable ON api_key_usage_events;
          CREATE TRIGGER api_key_usage_events_immutable
            BEFORE UPDATE OR DELETE ON api_key_usage_events
            FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
        `,
      });
    },
  },
];

export const POSTGRES_MFA_MIGRATIONS: readonly PostgresMigration[] = [
  {
    id: '025_account_mfa',
    up: async (database) => {
      await database.execute({
        text: `
          ALTER TABLE sessions
            ADD COLUMN IF NOT EXISTS authentication_method TEXT NOT NULL DEFAULT 'password';
          ALTER TABLE sessions ADD COLUMN IF NOT EXISTS mfa_authenticated_at TIMESTAMPTZ;

          CREATE TABLE IF NOT EXISTS user_mfa_factors (
            user_id INTEGER PRIMARY KEY,
            secret_workspace_id INTEGER NOT NULL,
            secret_ref TEXT NOT NULL UNIQUE,
            state TEXT NOT NULL CHECK(state IN ('pending', 'enabled')),
            last_used_step INTEGER NOT NULL DEFAULT -1,
            enabled_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
            FOREIGN KEY(secret_workspace_id) REFERENCES workspaces(id) ON DELETE RESTRICT
          );
          CREATE TABLE IF NOT EXISTS user_mfa_recovery_codes (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            code_hash TEXT NOT NULL UNIQUE,
            used_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
          );
          CREATE TABLE IF NOT EXISTS user_mfa_challenges (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            token_hash TEXT NOT NULL UNIQUE,
            purpose TEXT NOT NULL CHECK(purpose IN ('login', 'invitation')),
            context_json TEXT NOT NULL DEFAULT '{}',
            expires_at TIMESTAMPTZ NOT NULL,
            attempts INTEGER NOT NULL DEFAULT 0 CHECK(attempts >= 0),
            consumed_at TIMESTAMPTZ,
            revoked_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
          );
          CREATE TABLE IF NOT EXISTS user_mfa_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            event_type TEXT NOT NULL CHECK(event_type IN (
              'setup_started', 'enabled', 'disabled', 'recovery_codes_regenerated',
              'recovery_code_used', 'challenge_failed'
            )),
            metadata_json TEXT NOT NULL DEFAULT '{}',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
          );
          CREATE INDEX IF NOT EXISTS user_mfa_challenges_active_idx
            ON user_mfa_challenges(token_hash, expires_at, consumed_at, revoked_at);
          CREATE INDEX IF NOT EXISTS user_mfa_recovery_codes_active_idx
            ON user_mfa_recovery_codes(user_id, used_at);
          CREATE INDEX IF NOT EXISTS user_mfa_events_user_time_idx
            ON user_mfa_events(user_id, created_at DESC);
          DROP TRIGGER IF EXISTS user_mfa_events_immutable ON user_mfa_events;
          CREATE TRIGGER user_mfa_events_immutable
            BEFORE UPDATE OR DELETE ON user_mfa_events
            FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();
        `,
      });
    },
  },
];
