import { type PostgresMigration } from '../postgresMigrations';

export const POSTGRES_USAGE_MIGRATIONS: readonly PostgresMigration[] = [
  {
    id: '017_usage_rating_cost_controls',
    up: async (database) => {
      await database.execute({
        text: `
          CREATE TABLE IF NOT EXISTS pricing_versions (
            key TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'active',
            effective_from TIMESTAMPTZ NOT NULL,
            effective_to TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
          );

          CREATE TABLE IF NOT EXISTS meter_prices (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            pricing_version_key TEXT NOT NULL,
            meter TEXT NOT NULL,
            provider TEXT NOT NULL DEFAULT '*',
            model TEXT NOT NULL DEFAULT '*',
            unit_size INTEGER NOT NULL CHECK(unit_size > 0),
            credits_per_unit INTEGER NOT NULL CHECK(credits_per_unit >= 0),
            provider_cost_micros_per_unit INTEGER NOT NULL DEFAULT 0
              CHECK(provider_cost_micros_per_unit >= 0),
            active BOOLEAN NOT NULL DEFAULT TRUE,
            metadata_json TEXT NOT NULL DEFAULT '{}',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(pricing_version_key, meter, provider, model),
            FOREIGN KEY(pricing_version_key) REFERENCES pricing_versions(key)
          );

          CREATE TABLE IF NOT EXISTS rated_usage_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL,
            idempotency_key TEXT NOT NULL,
            meter TEXT NOT NULL,
            provider TEXT NOT NULL DEFAULT '',
            model TEXT NOT NULL DEFAULT '',
            quantity INTEGER NOT NULL CHECK(quantity >= 0),
            billable_units INTEGER NOT NULL CHECK(billable_units >= 0),
            credits_charged INTEGER NOT NULL CHECK(credits_charged >= 0),
            provider_cost_micros INTEGER NOT NULL DEFAULT 0 CHECK(provider_cost_micros >= 0),
            meter_price_id INTEGER NOT NULL,
            resource_type TEXT NOT NULL DEFAULT '',
            resource_id TEXT NOT NULL DEFAULT '',
            metadata_json TEXT NOT NULL DEFAULT '{}',
            occurred_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(workspace_id, idempotency_key),
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(meter_price_id) REFERENCES meter_prices(id)
          );

          CREATE TABLE IF NOT EXISTS workspace_cost_controls (
            workspace_id INTEGER PRIMARY KEY,
            monthly_credit_limit INTEGER CHECK(monthly_credit_limit IS NULL OR monthly_credit_limit >= 0),
            monthly_provider_cost_micros_limit INTEGER
              CHECK(monthly_provider_cost_micros_limit IS NULL OR monthly_provider_cost_micros_limit >= 0),
            hard_limit BOOLEAN NOT NULL DEFAULT TRUE,
            overage_enabled BOOLEAN NOT NULL DEFAULT FALSE,
            alert_thresholds_json TEXT NOT NULL DEFAULT '[50,80,100]',
            updated_by_user_id INTEGER,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
          );

          CREATE TABLE IF NOT EXISTS cost_alerts (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL,
            period_key TEXT NOT NULL,
            threshold_percent INTEGER NOT NULL,
            metric TEXT NOT NULL,
            current_value INTEGER NOT NULL,
            limit_value INTEGER NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            delivered_at TIMESTAMPTZ,
            UNIQUE(workspace_id, period_key, threshold_percent, metric),
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
          );

          DROP TRIGGER IF EXISTS rated_usage_events_immutable ON rated_usage_events;
          CREATE TRIGGER rated_usage_events_immutable
            BEFORE UPDATE OR DELETE ON rated_usage_events
            FOR EACH ROW EXECUTE FUNCTION primalthrum_reject_immutable_mutation();

          CREATE INDEX IF NOT EXISTS rated_usage_workspace_period_idx
            ON rated_usage_events(workspace_id, occurred_at, meter);
          CREATE INDEX IF NOT EXISTS rated_usage_resource_idx
            ON rated_usage_events(workspace_id, resource_type, resource_id);
        `,
      });

      await database.execute({
        text: `
          INSERT INTO pricing_versions (key, name, effective_from)
          VALUES ('2026-08-default', 'Initial commercial pricing', '2026-01-01T00:00:00.000Z')
          ON CONFLICT (key) DO NOTHING;

          INSERT INTO meter_prices (
            pricing_version_key, meter, unit_size, credits_per_unit,
            provider_cost_micros_per_unit
          ) VALUES
            ('2026-08-default', 'llm.input_tokens', 1000, 10, 1500),
            ('2026-08-default', 'llm.output_tokens', 1000, 30, 6000),
            ('2026-08-default', 'embedding.tokens', 1000, 2, 100),
            ('2026-08-default', 'speech.transcription_seconds', 60, 20, 6000),
            ('2026-08-default', 'speech.synthesis_characters', 1000, 15, 15000),
            ('2026-08-default', 'tool.calls', 1, 5, 0),
            ('2026-08-default', 'rag.retrievals', 1, 2, 0),
            ('2026-08-default', 'rag.storage_bytes', 1048576, 3, 0),
            ('2026-08-default', 'file.storage_bytes', 1048576, 2, 0),
            ('2026-08-default', 'hosted.runs', 1, 10, 0),
            ('2026-08-default', 'api.runs', 1, 10, 0)
          ON CONFLICT (pricing_version_key, meter, provider, model) DO NOTHING;
        `,
      });
    },
  },
  {
    id: '018_usage_meter_export_outbox',
    up: async (database) => {
      await database.execute({
        text: `
          CREATE TABLE IF NOT EXISTS usage_meter_exports (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            rated_usage_event_id INTEGER NOT NULL,
            destination TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending'
              CHECK(status IN ('pending', 'delivering', 'delivered', 'failed')),
            attempts INTEGER NOT NULL DEFAULT 0 CHECK(attempts >= 0),
            next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_error TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            delivered_at TIMESTAMPTZ,
            UNIQUE(rated_usage_event_id, destination),
            FOREIGN KEY(rated_usage_event_id) REFERENCES rated_usage_events(id) ON DELETE RESTRICT
          );

          CREATE INDEX IF NOT EXISTS usage_meter_exports_dispatch_idx
            ON usage_meter_exports(destination, status, next_attempt_at, id);

          CREATE OR REPLACE FUNCTION primalthrum_enqueue_meter_export()
          RETURNS TRIGGER LANGUAGE plpgsql AS $function$
          BEGIN
            INSERT INTO usage_meter_exports (rated_usage_event_id, destination)
            VALUES (NEW.id, 'primary')
            ON CONFLICT (rated_usage_event_id, destination) DO NOTHING;
            RETURN NEW;
          END;
          $function$;

          DROP TRIGGER IF EXISTS rated_usage_enqueue_meter_export ON rated_usage_events;
          CREATE TRIGGER rated_usage_enqueue_meter_export
            AFTER INSERT ON rated_usage_events
            FOR EACH ROW EXECUTE FUNCTION primalthrum_enqueue_meter_export();

          INSERT INTO usage_meter_exports (rated_usage_event_id, destination)
          SELECT id, 'primary' FROM rated_usage_events
          ON CONFLICT (rated_usage_event_id, destination) DO NOTHING;
        `,
      });
    },
  },
];
