import { type PostgresMigration } from '../postgresMigrations';
import { DEFAULT_WORKSPACE_ID } from '../workspaceDefaults';

export const POSTGRES_WORKSPACE_MIGRATIONS: readonly PostgresMigration[] = [
  {
    id: '009_workspace_memberships',
    up: async (database) => {
      await database.execute({
        text: `
          CREATE TABLE IF NOT EXISTS workspace_memberships (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            role TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'active',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(workspace_id, user_id),
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
          );

          CREATE TABLE IF NOT EXISTS workspace_invitations (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL,
            email TEXT NOT NULL,
            role TEXT NOT NULL,
            token_hash TEXT NOT NULL UNIQUE,
            invited_by_user_id INTEGER NOT NULL,
            expires_at TIMESTAMPTZ NOT NULL,
            accepted_at TIMESTAMPTZ,
            revoked_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
            FOREIGN KEY(invited_by_user_id) REFERENCES users(id) ON DELETE CASCADE
          );

          INSERT INTO workspace_memberships (workspace_id, user_id, role, status)
          SELECT
            workspace_id,
            id,
            CASE WHEN role = 'admin' THEN 'owner' ELSE 'member' END,
            'active'
          FROM users
          ON CONFLICT (workspace_id, user_id) DO NOTHING;

          ALTER TABLE provider_configs
            DROP CONSTRAINT IF EXISTS provider_configs_name_key;
          ALTER TABLE provider_configs
            ADD CONSTRAINT provider_configs_workspace_name_key UNIQUE (workspace_id, name);

          ALTER TABLE sessions
            ADD COLUMN IF NOT EXISTS active_workspace_id INTEGER NOT NULL DEFAULT ${DEFAULT_WORKSPACE_ID};
          UPDATE sessions
          SET active_workspace_id = workspace_id
          WHERE active_workspace_id IS NULL;
        `,
      });
    },
  },
];
