import type { GeneratedAgentTemplateInput, TemplateFile } from './templateTypes';

export function metadataTemplates(input: GeneratedAgentTemplateInput): TemplateFile[] {
  const configJson = JSON.stringify(
    {
      agent: {
        name: input.name,
        slug: input.slug,
        description: input.description,
      },
      runtime: input.runtime,
    },
    null,
    2,
  );

  return [
    {
      path: 'README.md',
      content: `# ${input.name}

Generated by Primalthrum.

## Web App

\`\`\`bash
python -m pip install -e .
python -m uvicorn src.app:app --host 0.0.0.0 --port 8000
\`\`\`

Open http://localhost:8000. The page supports text input, browser speech input,
and browser speech playback.

## CLI

\`\`\`bash
python -m src.main "Summarize the current task"
\`\`\`

The generated configuration preserves the selected memory, cache, tools, skills,
and RAG settings in \`src/config.json\`.
`,
    },
    {
      path: '.env.example',
      content: `LLM_PROVIDER=mock
LLM_MODEL=mock-chat
EMBEDDING_MODEL=mock-embedding
`,
    },
    {
      path: 'pyproject.toml',
      content: `[project]
name = "${input.slug}"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.115,<1.0",
  "langgraph>=0.2,<1.0",
  "uvicorn>=0.30,<1.0",
]
`,
    },
    {
      path: 'src/__init__.py',
      content: '',
    },
    {
      path: 'src/config.json',
      content: `${configJson}\n`,
    },
    {
      path: 'src/config.py',
      content: `from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def load_config() -> dict[str, Any]:
    return json.loads((Path(__file__).with_name("config.json")).read_text(encoding="utf-8"))
`,
    },
  ];
}
