import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import type { AgentRecord } from '../services/agentRepository';

export interface GeneratedProject {
  path: string;
  files: string[];
}

interface TemplateFile {
  path: string;
  content: string;
}

export async function generateAgentProject(agent: AgentRecord): Promise<GeneratedProject> {
  const files = templateFiles(agent);

  await mkdir(agent.path, { recursive: true });
  for (const file of files) {
    const target = join(agent.path, file.path);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, file.content, 'utf8');
  }

  return {
    path: agent.path,
    files: files.map((file) => file.path),
  };
}

function templateFiles(agent: AgentRecord): TemplateFile[] {
  const configJson = JSON.stringify(
    {
      agent: {
        name: agent.name,
        slug: agent.slug,
        description: agent.description,
      },
      runtime: agent.config,
    },
    null,
    2,
  );

  return [
    {
      path: 'README.md',
      content: `# ${agent.name}

Generated by Primalthrum.

## Run

\`\`\`bash
python -m src.main "Summarize the current task"
\`\`\`

This agent uses a fixed LangGraph template with configurable memory, cache, tools, skills, and RAG providers.
`,
    },
    {
      path: '.env.example',
      content: `LLM_PROVIDER=mock
LLM_MODEL=mock-chat
EMBEDDING_MODEL=mock-embedding
`,
    },
    {
      path: 'pyproject.toml',
      content: `[project]
name = "${agent.slug}"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["langgraph"]
`,
    },
    {
      path: 'src/__init__.py',
      content: '',
    },
    {
      path: 'src/config.json',
      content: `${configJson}
`,
    },
    {
      path: 'src/config.py',
      content: `from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def load_config() -> dict[str, Any]:
    return json.loads((Path(__file__).with_name("config.json")).read_text(encoding="utf-8"))
`,
    },
    {
      path: 'src/main.py',
      content: `from __future__ import annotations

import sys

from .graph import build_graph


def main() -> None:
    task = sys.argv[1] if len(sys.argv) > 1 else "Run the demo task"
    graph = build_graph()
    result = graph.invoke({"task": task, "events": []})
    print(result["answer"])


if __name__ == "__main__":
    main()
`,
    },
    {
      path: 'src/graph.py',
      content: `from __future__ import annotations

from typing import TypedDict

from langgraph.graph import END, StateGraph

from .nodes.act_with_tools import act_with_tools
from .nodes.finalize import finalize
from .nodes.load_context import load_context
from .nodes.plan import plan
from .nodes.retrieve_optional_rag import retrieve_optional_rag
from .nodes.update_memory import update_memory


class AgentState(TypedDict):
    task: str
    events: list[str]
    answer: str


def build_graph():
    graph = StateGraph(AgentState)
    graph.add_node("load_context", load_context)
    graph.add_node("plan", plan)
    graph.add_node("retrieve_optional_rag", retrieve_optional_rag)
    graph.add_node("act_with_tools", act_with_tools)
    graph.add_node("update_memory", update_memory)
    graph.add_node("finalize", finalize)
    graph.set_entry_point("load_context")
    graph.add_edge("load_context", "plan")
    graph.add_edge("plan", "retrieve_optional_rag")
    graph.add_edge("retrieve_optional_rag", "act_with_tools")
    graph.add_edge("act_with_tools", "update_memory")
    graph.add_edge("update_memory", "finalize")
    graph.add_edge("finalize", END)
    return graph.compile()
`,
    },
    {
      path: 'src/nodes/__init__.py',
      content: '',
    },
    {
      path: 'src/nodes/load_context.py',
      content: `from __future__ import annotations


def load_context(state: dict) -> dict:
    return {"events": state["events"] + ["load_context"]}
`,
    },
    {
      path: 'src/nodes/plan.py',
      content: `from __future__ import annotations


def plan(state: dict) -> dict:
    return {"events": state["events"] + ["plan"]}
`,
    },
    {
      path: 'src/nodes/retrieve_optional_rag.py',
      content: `from __future__ import annotations

from ..config import load_config


def retrieve_optional_rag(state: dict) -> dict:
    config = load_config()
    rag_provider = config["runtime"].get("ragProvider", "none")
    event = "rag_skipped" if rag_provider in {"none", "null"} else "rag_retrieved"
    return {"events": state["events"] + [event]}
`,
    },
    {
      path: 'src/nodes/act_with_tools.py',
      content: `from __future__ import annotations

from ..config import load_config


def act_with_tools(state: dict) -> dict:
    config = load_config()
    tools = ", ".join(config["runtime"].get("enabledTools", [])) or "no tools"
    answer = f"Planned task: {state['task']} with {tools}."
    return {"events": state["events"] + ["act_with_tools"], "answer": answer}
`,
    },
    {
      path: 'src/nodes/update_memory.py',
      content: `from __future__ import annotations


def update_memory(state: dict) -> dict:
    return {"events": state["events"] + ["update_memory"]}
`,
    },
    {
      path: 'src/nodes/finalize.py',
      content: `from __future__ import annotations


def finalize(state: dict) -> dict:
    return {"events": state["events"] + ["finalize"]}
`,
    },
    ...placeholderPackages(['providers', 'tools', 'skills', 'rag', 'memory', 'cache']),
    {
      path: 'tests/test_demo.py',
      content: `from src.graph import build_graph


def test_demo_graph_runs():
    graph = build_graph()
    result = graph.invoke({"task": "demo", "events": []})
    assert "answer" in result
    assert "rag_skipped" in result["events"]
`,
    },
  ];
}

function placeholderPackages(names: string[]): TemplateFile[] {
  return names.map((name) => ({
    path: `src/${name}/__init__.py`,
    content: '',
  }));
}
